version: "3.6"
services:

  edge-app:
    container_name: edge-app
    image: zomco/hqsms:latest
    ports:
      - "58080:8080"
    restart: always
    depends_on:
      - edge-mysql
      - edge-redis
    volumes:
      - "${EDGE_DATA:-~/edge}/app/file:/home/file"
      - "${EDGE_DATA:-~/edge}/app/log:/home/log"
      - "${EDGE_DATA:-~/edge}/app/tmp:/home/tmp"
    links:
      - edge-mysql
      - edge-redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://edge-mysql:3306/hqsms?useUnicode=true&characterEncoding=utf8&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=hqsms
      - SPRING_RABBITMQ_HOST=${CLOUD_IP}
      - SPRING_RABBITMQ_PORT=${CLOUD_RABBITMQ_PORT}
      - SPRING_RABBITMQ_USERNAME=hqsms
      - SPRING_RABBITMQ_PASSWORD=hqsms
      - SPRING_REDIS_HOST=edge-redis
      - SPRING_REDIS_PORT=6379
      - HQSMS_CLOUD_SERVER_ENABLE=false
      - HQSMS_CLOUD_SERVER_HOST=${CLOUD_IP}
      - HQSMS_CLOUD_SERVER_PORT=${CLOUD_APP_PORT}
      - HQSMS_CLOUD_SRS_API_PORT=${CLOUD_SRS_API_PORT}
      - HQSMS_CLOUD_SRS_HLS_PORT=${CLOUD_SRS_HLS_PORT}
      - HQSMS_EDGE_SERVER_ENABLE=true
      - HQSMS_EDGE_CAMERA_ENABLE=true
      - HQSMS_EDGE_WEATHER_ENABLE=false
      - HQSMS_EDGE_BROADCAST_ENABLE=false
      - HQSMS_EDGE_SCREEN_ENABLE=false
      - HQSMS_EDGE_WIFI_ENABLE=false
      - HQSMS_EDGE_ALARM_ENABLE=false
      - HQSMS_EDGE_CHARGER_ENABLE=false
      - HQSMS_EDGE_METER_ENABLE=false
      - LEAF_SEGMENT_URL=jdbc:mysql://${CLOUD_IP}:${CLOUD_MYSQL_PORT}/leaf?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - LEAF_SEGMENT_USERNAME=root
      - LEAF_SEGMENT_PASSWORD=hqsms
      - LEAF_JDBC_URL=jdbc:mysql://${CLOUD_IP}:${CLOUD_MYSQL_PORT}/leaf?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - LEAF_JDBC_USERNAME=root
      - LEAF_JDBC_PASSWORD=hqsms
      - LD_LIBRARY_PATH=/home/sdk/linux-x86-64/hikvision;/home/sdk/linux-x86-64/hikvision/HCNetSDKCom;/home/sdk/linux-x86-64/huawei;/home/sdk/linux-x86-64/huawei/lib64
    command: ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "app.jar"]

  edge-redis:
    container_name: edge-redis
    image: redis
    restart: always
    volumes:
      - "${EDGE_DATA:-~/edge}/redis/data:/data"

  edge-mysql:
    container_name: edge-mysql
    image: mysql
    ports:
      - "53306:3306"
    restart: always
    volumes:
      - "${EDGE_DATA:-~/edge}/mysql/data:/var/lib/mysql"
      - "${EDGE_DATA:-~/edge}/mysql/log:/var/log/mysql"
      - "./conf/edge/mysql/init:/docker-entrypoint-initdb.d"
      - "./conf/edge/mysql/sql:/opt/sql"
    environment:
      - MYSQL_DATABASE=hqsms
      - MYSQL_USER=hqsms
      - MYSQL_PASSWORD=hqsms
      - MYSQL_ROOT_PASSWORD=hqsms
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-ssl --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci